### ISSUE TITLE
Generating code free of max/min

### ISSUE THREAD

**Issue by tjingrant** [Meinersbur/isl#3]
Dear isl developer:

I'm curious is there any way of eliminating max/min in the output code generation? It would make more sense to have more blocks of code that branches at a shallower loop depth than less blocks of code but with max/mins at a deeper loop depth. This seems to be a common pattern and I wonder if anyone has come up with anything in the past to achieve it.

I can see there's ast_build_detect_min_max option in the manual, but it doesn't say much.. Can you give me some pointers/hints?

Best wishes,
Tian Jin.

**Comment by Meinersbur** [comment]
Did you try switching off max/min detection (`isl_options_set_ast_build_detect_min_max(ctx, 0)`)? It should switch it off.

A more detailed description is in isl_ast_build_expr.c:
```
/* Can the list of subpieces in the last piece of "data" be extended with
 * "set" and "aff" based on "test"?
 * In particular, is it the case for each entry (set_i, aff_i) that
 *
 *	test(aff, aff_i) holds on set_i, and
 *	test(aff_i, aff) holds on set?
 *
 * "test" returns the set of elements where the tests holds, meaning
 * that test(aff_i, aff) holds on set if set is a subset of test(aff_i, aff).
 *
 * This function is used to detect min/max expressions.
 * If the ast_build_detect_min_max option is turned off, then
 * do not even try and perform any detection and return false instead.
 *
 * Rational affine expressions are not considered for min/max expressions
 * since the combined expression will be defined on the union of the domains,
 * while a rational expression may only yield integer values
 * on its own definition domain.
 */
```

I don't understand the motivation. If subexpressions can be hoisted out of loops, the compiler should be able to do that. You can also control what min/max expands to. There is also `isl_ast_op_type_print_macro` which print the following macro:
```
#define min(x,y)    ((x) > (y) ? (x) : (y))
```
i.e. min/max disappear anyway.

PS: The official discussion forum is https://groups.google.com/forum/#!forum/isl-development

**Comment by tjingrant** [comment]
thanks for the reply, the discussion is moved to isl-development. Let's close this issue.
