### ISSUE TITLE
Question about cmake support

### ISSUE THREAD

**Issue by vmiheer** [Meinersbur/isl#4]
Looking at https://github.com/Meinersbur/isl/blob/cmake/configure.ac#L86-L90, seems like when using `configure` scripts, default is gmp. But in cmake, seems like https://github.com/Meinersbur/isl/blob/8bee467c7170c47653e04e16e49a2e190d1440f4/CMakeLists.txt#L24 makes small int opt default. 

To get it built with gmp, it needs both:
`ISL_INT: gmp` and `ISL_SMALL_INT_OPT: OFF`

I wonder if this is intended.

**Comment by Meinersbur** [comment]
This is intended, as I usually work with imath-sio32 and saves me from changing it every time. If you think it would be better to be consistent with the autoconf configuration, I would accept a pull request for that.

We intended a small integer optimization for gmp as well (my original design for sio was to be independent of which the underlying big integer implementation was), such that the ISL_SMALL_INT_OPT and ISL_INT setting would be orthogonal.

As by https://github.com/Meinersbur/isl/blob/8bee467c7170c47653e04e16e49a2e190d1440f4/CMakeLists.txt#L333-L337 ISL_SMALL_INT_OPT should be ignored if ISL_INT is set to `gmp`.

**Comment by vmiheer** [comment]
Okay here's the source of bug:
1. cmake sets `ISL_SMALL_INT_OPT` to `ON`.
2. This sets `USE_SMALL_INT_OPT` to `ON`.
3. Now if `USE_GMP_FOR_MP` is `ON`, even though `libisl_imath32_sources` are not added to `libisl_sources`, `isl_config.h.cmake` still sets `USE_SMALL_INT_OPT` in `isl_config.h`
4. The macro `USE_SMALL_INT_OPT` disables macro `isl_int_print` `isl_int.h`
5. This ultimately causes linker error:  `unresolved external symbol isl_int_print`.
